# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: MkDocs Material Template
site_description: Template for MkDocs Material
site_author: Daniel A. A. Pelsmaeker

repo_url: https://github.com/Virtlink/mkdocs-material-template
edit_uri: https://github.com/Virtlink/mkdocs-material-template/edit/main/docs

theme:
  name: material
  language: en
  icon:
    logo: fontawesome/solid/book
    repo: fontawesome/brands/github
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    code: "JetBrains Mono"
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - content.code.annotate
    
extra_css:
  - assets/styles.css
extra_javascript:
  - assets/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      guess_lang: false
  - pymdownx.inlinehilite:
      custom_inline:
        - name: gui
          class: guilabel
          format: !!python/name:formatters.inline_span_format
  - pymdownx.keys:
      key_map:
        click: "Click"
        left-click: "Left Click"
        right-click: "Right Click"
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - git-revision-date:
      enabled_if_env: CI
  - macros:
      module_name: tools/macro
